[2021-05-08 20:18:39,167] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: dag_4.python_push_into_target 2021-05-07T00:00:00+00:00 [queued]>
[2021-05-08 20:18:39,178] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: dag_4.python_push_into_target 2021-05-07T00:00:00+00:00 [queued]>
[2021-05-08 20:18:39,178] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-08 20:18:39,178] {taskinstance.py:1069} INFO - Starting attempt 6 of 8
[2021-05-08 20:18:39,179] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-08 20:18:39,340] {taskinstance.py:1089} INFO - Executing <Task(PythonOperator): python_push_into_target> on 2021-05-07T00:00:00+00:00
[2021-05-08 20:18:39,344] {standard_task_runner.py:52} INFO - Started process 5324 to run task
[2021-05-08 20:18:39,350] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dag_4', 'python_push_into_target', '2021-05-07T00:00:00+00:00', '--job-id', '97', '--pool', 'default_pool', '--raw', '--subdir', '/home/navneetsajwan/airflow/dags/dag__4.py', '--cfg-path', '/tmp/tmpezo_6au9', '--error-file', '/tmp/tmpn0n2_bdy']
[2021-05-08 20:18:39,351] {standard_task_runner.py:77} INFO - Job 97: Subtask python_push_into_target
[2021-05-08 20:18:39,478] {logging_mixin.py:104} INFO - Running <TaskInstance: dag_4.python_push_into_target 2021-05-07T00:00:00+00:00 [running]> on host navneetsajwan-Lenovo-G50-80
[2021-05-08 20:18:39,504] {taskinstance.py:1281} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=navneet@metaorigins.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dag_4
AIRFLOW_CTX_TASK_ID=python_push_into_target
AIRFLOW_CTX_EXECUTION_DATE=2021-05-07T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-05-07T00:00:00+00:00
[2021-05-08 20:18:44,011] {logging_mixin.py:104} INFO - push_test
[2021-05-08 20:18:44,012] {python.py:118} INFO - Done. Returned value was: None
[2021-05-08 20:18:44,016] {taskinstance.py:1185} INFO - Marking task as SUCCESS. dag_id=dag_4, task_id=python_push_into_target, execution_date=20210507T000000, start_date=20210508T144839, end_date=20210508T144844
[2021-05-08 20:18:44,185] {taskinstance.py:1246} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-05-08 20:18:44,214] {local_task_job.py:146} INFO - Task exited with return code 0
