[2021-05-09 19:18:04,643] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: dag_4.python_push_into_target 2021-05-07T00:00:00+00:00 [queued]>
[2021-05-09 19:18:04,658] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: dag_4.python_push_into_target 2021-05-07T00:00:00+00:00 [queued]>
[2021-05-09 19:18:04,659] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-09 19:18:04,659] {taskinstance.py:1069} INFO - Starting attempt 9 of 11
[2021-05-09 19:18:04,659] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-09 19:18:04,808] {taskinstance.py:1089} INFO - Executing <Task(PythonOperator): python_push_into_target> on 2021-05-07T00:00:00+00:00
[2021-05-09 19:18:04,812] {standard_task_runner.py:52} INFO - Started process 20685 to run task
[2021-05-09 19:18:04,820] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dag_4', 'python_push_into_target', '2021-05-07T00:00:00+00:00', '--job-id', '141', '--pool', 'default_pool', '--raw', '--subdir', '/home/navneetsajwan/airflow/dags/dag__4.py', '--cfg-path', '/tmp/tmpyjjlc6c0', '--error-file', '/tmp/tmps7l5zra3']
[2021-05-09 19:18:04,821] {standard_task_runner.py:77} INFO - Job 141: Subtask python_push_into_target
[2021-05-09 19:18:04,970] {logging_mixin.py:104} INFO - Running <TaskInstance: dag_4.python_push_into_target 2021-05-07T00:00:00+00:00 [running]> on host navneetsajwan-Lenovo-G50-80
[2021-05-09 19:18:05,016] {taskinstance.py:1281} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=navneet@metaorigins.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dag_4
AIRFLOW_CTX_TASK_ID=python_push_into_target
AIRFLOW_CTX_EXECUTION_DATE=2021-05-07T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-05-07T00:00:00+00:00
[2021-05-09 19:18:06,269] {logging_mixin.py:104} INFO - push_test
[2021-05-09 19:18:06,269] {python.py:118} INFO - Done. Returned value was: None
[2021-05-09 19:18:06,274] {taskinstance.py:1185} INFO - Marking task as SUCCESS. dag_id=dag_4, task_id=python_push_into_target, execution_date=20210507T000000, start_date=20210509T134804, end_date=20210509T134806
[2021-05-09 19:18:06,438] {taskinstance.py:1246} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-05-09 19:18:06,481] {local_task_job.py:146} INFO - Task exited with return code 0
