[2021-05-08 01:24:14,511] {scheduler_job.py:182} INFO - Started process (PID=457593) to work on /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:24:14,523] {scheduler_job.py:629} INFO - Processing file /home/navneetsajwan/airflow/dags/sql_to_csv.py for tasks to queue
[2021-05-08 01:24:14,524] {logging_mixin.py:104} INFO - [2021-05-08 01:24:14,524] {dagbag.py:451} INFO - Filling up the DagBag from /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:24:14,582] {logging_mixin.py:104} INFO - [2021-05-08 01:24:14,576] {dagbag.py:308} ERROR - Failed to import: /home/navneetsajwan/airflow/dags/sql_to_csv.py
Traceback (most recent call last):
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/navneetsajwan/airflow/dags/sql_to_csv.py", line 9, in <module>
    from  mysql_to_csv import tap_mysql_target_csv,today_dir,move_files,detect_schemas,state_file
ModuleNotFoundError: No module named 'mysql_to_csv'
[2021-05-08 01:24:14,583] {scheduler_job.py:641} WARNING - No viable dags retrieved from /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:24:14,764] {scheduler_job.py:190} INFO - Processing /home/navneetsajwan/airflow/dags/sql_to_csv.py took 0.269 seconds
[2021-05-08 01:24:49,169] {scheduler_job.py:182} INFO - Started process (PID=458081) to work on /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:24:49,171] {scheduler_job.py:629} INFO - Processing file /home/navneetsajwan/airflow/dags/sql_to_csv.py for tasks to queue
[2021-05-08 01:24:49,174] {logging_mixin.py:104} INFO - [2021-05-08 01:24:49,174] {dagbag.py:451} INFO - Filling up the DagBag from /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:24:49,185] {logging_mixin.py:104} INFO - [2021-05-08 01:24:49,183] {dagbag.py:308} ERROR - Failed to import: /home/navneetsajwan/airflow/dags/sql_to_csv.py
Traceback (most recent call last):
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/navneetsajwan/airflow/dags/sql_to_csv.py", line 9, in <module>
    from  mysql_to_csv import tap_mysql_target_csv,today_dir,move_files,detect_schemas,state_file
ModuleNotFoundError: No module named 'mysql_to_csv'
[2021-05-08 01:24:49,185] {scheduler_job.py:641} WARNING - No viable dags retrieved from /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:24:49,277] {scheduler_job.py:190} INFO - Processing /home/navneetsajwan/airflow/dags/sql_to_csv.py took 0.114 seconds
[2021-05-08 01:25:51,127] {scheduler_job.py:182} INFO - Started process (PID=459141) to work on /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:25:51,139] {scheduler_job.py:629} INFO - Processing file /home/navneetsajwan/airflow/dags/sql_to_csv.py for tasks to queue
[2021-05-08 01:25:51,140] {logging_mixin.py:104} INFO - [2021-05-08 01:25:51,140] {dagbag.py:451} INFO - Filling up the DagBag from /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:25:51,165] {logging_mixin.py:104} INFO - [2021-05-08 01:25:51,164] {dagbag.py:308} ERROR - Failed to import: /home/navneetsajwan/airflow/dags/sql_to_csv.py
Traceback (most recent call last):
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/navneetsajwan/airflow/dags/sql_to_csv.py", line 9, in <module>
    from  mysql_to_csv import tap_mysql_target_csv,today_dir,move_files,detect_schemas,state_file
ModuleNotFoundError: No module named 'mysql_to_csv'
[2021-05-08 01:25:51,166] {scheduler_job.py:641} WARNING - No viable dags retrieved from /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:25:52,262] {scheduler_job.py:190} INFO - Processing /home/navneetsajwan/airflow/dags/sql_to_csv.py took 1.145 seconds
[2021-05-08 01:26:46,028] {scheduler_job.py:182} INFO - Started process (PID=460270) to work on /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:26:46,030] {scheduler_job.py:629} INFO - Processing file /home/navneetsajwan/airflow/dags/sql_to_csv.py for tasks to queue
[2021-05-08 01:26:46,046] {logging_mixin.py:104} INFO - [2021-05-08 01:26:46,045] {dagbag.py:451} INFO - Filling up the DagBag from /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:26:46,068] {logging_mixin.py:104} INFO - [2021-05-08 01:26:46,067] {dagbag.py:308} ERROR - Failed to import: /home/navneetsajwan/airflow/dags/sql_to_csv.py
Traceback (most recent call last):
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/navneetsajwan/airflow/dags/sql_to_csv.py", line 9, in <module>
    from  mysql_to_csv import tap_mysql_target_csv,today_dir,move_files,detect_schemas,state_file
ModuleNotFoundError: No module named 'mysql_to_csv'
[2021-05-08 01:26:46,080] {scheduler_job.py:641} WARNING - No viable dags retrieved from /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:26:46,418] {scheduler_job.py:190} INFO - Processing /home/navneetsajwan/airflow/dags/sql_to_csv.py took 0.397 seconds
[2021-05-08 01:27:21,886] {scheduler_job.py:182} INFO - Started process (PID=460818) to work on /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:27:21,900] {scheduler_job.py:629} INFO - Processing file /home/navneetsajwan/airflow/dags/sql_to_csv.py for tasks to queue
[2021-05-08 01:27:21,915] {logging_mixin.py:104} INFO - [2021-05-08 01:27:21,915] {dagbag.py:451} INFO - Filling up the DagBag from /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:27:21,975] {logging_mixin.py:104} INFO - [2021-05-08 01:27:21,962] {dagbag.py:308} ERROR - Failed to import: /home/navneetsajwan/airflow/dags/sql_to_csv.py
Traceback (most recent call last):
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/navneetsajwan/airflow/dags/sql_to_csv.py", line 9, in <module>
    from  mysql_to_csv import tap_mysql_target_csv,today_dir,move_files,detect_schemas,state_file
ModuleNotFoundError: No module named 'mysql_to_csv'
[2021-05-08 01:27:21,985] {scheduler_job.py:641} WARNING - No viable dags retrieved from /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:27:22,290] {scheduler_job.py:190} INFO - Processing /home/navneetsajwan/airflow/dags/sql_to_csv.py took 0.421 seconds
[2021-05-08 01:28:11,905] {scheduler_job.py:182} INFO - Started process (PID=461864) to work on /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:28:11,923] {scheduler_job.py:629} INFO - Processing file /home/navneetsajwan/airflow/dags/sql_to_csv.py for tasks to queue
[2021-05-08 01:28:11,933] {logging_mixin.py:104} INFO - [2021-05-08 01:28:11,931] {dagbag.py:451} INFO - Filling up the DagBag from /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:28:11,982] {logging_mixin.py:104} INFO - [2021-05-08 01:28:11,980] {dagbag.py:308} ERROR - Failed to import: /home/navneetsajwan/airflow/dags/sql_to_csv.py
Traceback (most recent call last):
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/navneetsajwan/airflow/dags/sql_to_csv.py", line 9, in <module>
    from  mysql_to_csv import tap_mysql_target_csv,today_dir,move_files,detect_schemas,state_file
ModuleNotFoundError: No module named 'mysql_to_csv'
[2021-05-08 01:28:11,982] {scheduler_job.py:641} WARNING - No viable dags retrieved from /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:28:12,141] {scheduler_job.py:190} INFO - Processing /home/navneetsajwan/airflow/dags/sql_to_csv.py took 0.250 seconds
[2021-05-08 01:29:22,684] {scheduler_job.py:182} INFO - Started process (PID=462838) to work on /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:29:22,685] {scheduler_job.py:629} INFO - Processing file /home/navneetsajwan/airflow/dags/sql_to_csv.py for tasks to queue
[2021-05-08 01:29:22,686] {logging_mixin.py:104} INFO - [2021-05-08 01:29:22,686] {dagbag.py:451} INFO - Filling up the DagBag from /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:29:22,714] {logging_mixin.py:104} INFO - [2021-05-08 01:29:22,713] {dagbag.py:308} ERROR - Failed to import: /home/navneetsajwan/airflow/dags/sql_to_csv.py
Traceback (most recent call last):
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/navneetsajwan/airflow/dags/sql_to_csv.py", line 9, in <module>
    from  mysql_to_csv import tap_mysql_target_csv,today_dir,move_files,detect_schemas,state_file
ModuleNotFoundError: No module named 'mysql_to_csv'
[2021-05-08 01:29:22,715] {scheduler_job.py:641} WARNING - No viable dags retrieved from /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:29:22,849] {scheduler_job.py:190} INFO - Processing /home/navneetsajwan/airflow/dags/sql_to_csv.py took 0.189 seconds
[2021-05-08 01:30:11,374] {scheduler_job.py:182} INFO - Started process (PID=463856) to work on /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:30:11,377] {scheduler_job.py:629} INFO - Processing file /home/navneetsajwan/airflow/dags/sql_to_csv.py for tasks to queue
[2021-05-08 01:30:11,378] {logging_mixin.py:104} INFO - [2021-05-08 01:30:11,378] {dagbag.py:451} INFO - Filling up the DagBag from /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:30:11,391] {logging_mixin.py:104} INFO - [2021-05-08 01:30:11,390] {dagbag.py:308} ERROR - Failed to import: /home/navneetsajwan/airflow/dags/sql_to_csv.py
Traceback (most recent call last):
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/navneetsajwan/airflow/dags/sql_to_csv.py", line 9, in <module>
    from  mysql_to_csv import tap_mysql_target_csv,today_dir,move_files,detect_schemas,state_file
ModuleNotFoundError: No module named 'mysql_to_csv'
[2021-05-08 01:30:11,392] {scheduler_job.py:641} WARNING - No viable dags retrieved from /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:30:11,530] {scheduler_job.py:190} INFO - Processing /home/navneetsajwan/airflow/dags/sql_to_csv.py took 0.159 seconds
[2021-05-08 01:30:48,586] {scheduler_job.py:182} INFO - Started process (PID=464392) to work on /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:30:48,588] {scheduler_job.py:629} INFO - Processing file /home/navneetsajwan/airflow/dags/sql_to_csv.py for tasks to queue
[2021-05-08 01:30:48,589] {logging_mixin.py:104} INFO - [2021-05-08 01:30:48,588] {dagbag.py:451} INFO - Filling up the DagBag from /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:30:48,600] {logging_mixin.py:104} INFO - [2021-05-08 01:30:48,599] {dagbag.py:308} ERROR - Failed to import: /home/navneetsajwan/airflow/dags/sql_to_csv.py
Traceback (most recent call last):
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/navneetsajwan/airflow/dags/sql_to_csv.py", line 9, in <module>
    from  mysql_to_csv import tap_mysql_target_csv,today_dir,move_files,detect_schemas,state_file
ModuleNotFoundError: No module named 'mysql_to_csv'
[2021-05-08 01:30:48,601] {scheduler_job.py:641} WARNING - No viable dags retrieved from /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:30:48,744] {scheduler_job.py:190} INFO - Processing /home/navneetsajwan/airflow/dags/sql_to_csv.py took 0.162 seconds
[2021-05-08 01:31:25,372] {scheduler_job.py:182} INFO - Started process (PID=465283) to work on /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:31:25,408] {scheduler_job.py:629} INFO - Processing file /home/navneetsajwan/airflow/dags/sql_to_csv.py for tasks to queue
[2021-05-08 01:31:25,409] {logging_mixin.py:104} INFO - [2021-05-08 01:31:25,409] {dagbag.py:451} INFO - Filling up the DagBag from /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:31:25,501] {logging_mixin.py:104} INFO - [2021-05-08 01:31:25,500] {dagbag.py:308} ERROR - Failed to import: /home/navneetsajwan/airflow/dags/sql_to_csv.py
Traceback (most recent call last):
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/navneetsajwan/airflow/dags/sql_to_csv.py", line 9, in <module>
    from  mysql_to_csv import tap_mysql_target_csv,today_dir,move_files,detect_schemas,state_file
ModuleNotFoundError: No module named 'mysql_to_csv'
[2021-05-08 01:31:25,502] {scheduler_job.py:641} WARNING - No viable dags retrieved from /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:31:25,680] {scheduler_job.py:190} INFO - Processing /home/navneetsajwan/airflow/dags/sql_to_csv.py took 0.327 seconds
[2021-05-08 01:32:08,413] {scheduler_job.py:182} INFO - Started process (PID=465901) to work on /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:32:08,423] {scheduler_job.py:629} INFO - Processing file /home/navneetsajwan/airflow/dags/sql_to_csv.py for tasks to queue
[2021-05-08 01:32:08,424] {logging_mixin.py:104} INFO - [2021-05-08 01:32:08,424] {dagbag.py:451} INFO - Filling up the DagBag from /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:32:08,457] {logging_mixin.py:104} INFO - [2021-05-08 01:32:08,455] {dagbag.py:308} ERROR - Failed to import: /home/navneetsajwan/airflow/dags/sql_to_csv.py
Traceback (most recent call last):
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/navneetsajwan/airflow/dags/sql_to_csv.py", line 9, in <module>
    from  mysql_to_csv import tap_mysql_target_csv,today_dir,move_files,detect_schemas,state_file
ModuleNotFoundError: No module named 'mysql_to_csv'
[2021-05-08 01:32:08,457] {scheduler_job.py:641} WARNING - No viable dags retrieved from /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:32:08,803] {scheduler_job.py:190} INFO - Processing /home/navneetsajwan/airflow/dags/sql_to_csv.py took 0.402 seconds
[2021-05-08 01:32:49,001] {scheduler_job.py:182} INFO - Started process (PID=466522) to work on /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:32:49,002] {scheduler_job.py:629} INFO - Processing file /home/navneetsajwan/airflow/dags/sql_to_csv.py for tasks to queue
[2021-05-08 01:32:49,003] {logging_mixin.py:104} INFO - [2021-05-08 01:32:49,003] {dagbag.py:451} INFO - Filling up the DagBag from /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:32:49,011] {logging_mixin.py:104} INFO - [2021-05-08 01:32:49,010] {dagbag.py:308} ERROR - Failed to import: /home/navneetsajwan/airflow/dags/sql_to_csv.py
Traceback (most recent call last):
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/navneetsajwan/airflow/dags/sql_to_csv.py", line 9, in <module>
    from  mysql_to_csv import tap_mysql_target_csv,today_dir,move_files,detect_schemas,state_file
ModuleNotFoundError: No module named 'mysql_to_csv'
[2021-05-08 01:32:49,012] {scheduler_job.py:641} WARNING - No viable dags retrieved from /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:32:49,272] {scheduler_job.py:190} INFO - Processing /home/navneetsajwan/airflow/dags/sql_to_csv.py took 0.274 seconds
[2021-05-08 01:33:30,362] {scheduler_job.py:182} INFO - Started process (PID=467400) to work on /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:33:30,365] {scheduler_job.py:629} INFO - Processing file /home/navneetsajwan/airflow/dags/sql_to_csv.py for tasks to queue
[2021-05-08 01:33:30,366] {logging_mixin.py:104} INFO - [2021-05-08 01:33:30,366] {dagbag.py:451} INFO - Filling up the DagBag from /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:33:30,383] {logging_mixin.py:104} INFO - [2021-05-08 01:33:30,381] {dagbag.py:308} ERROR - Failed to import: /home/navneetsajwan/airflow/dags/sql_to_csv.py
Traceback (most recent call last):
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/navneetsajwan/airflow/dags/sql_to_csv.py", line 9, in <module>
    from  mysql_to_csv import tap_mysql_target_csv,today_dir,move_files,detect_schemas,state_file
ModuleNotFoundError: No module named 'mysql_to_csv'
[2021-05-08 01:33:30,384] {scheduler_job.py:641} WARNING - No viable dags retrieved from /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:33:30,509] {scheduler_job.py:190} INFO - Processing /home/navneetsajwan/airflow/dags/sql_to_csv.py took 0.153 seconds
[2021-05-08 01:34:04,778] {scheduler_job.py:182} INFO - Started process (PID=467890) to work on /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:34:04,789] {scheduler_job.py:629} INFO - Processing file /home/navneetsajwan/airflow/dags/sql_to_csv.py for tasks to queue
[2021-05-08 01:34:04,791] {logging_mixin.py:104} INFO - [2021-05-08 01:34:04,790] {dagbag.py:451} INFO - Filling up the DagBag from /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:34:04,858] {logging_mixin.py:104} INFO - [2021-05-08 01:34:04,857] {dagbag.py:308} ERROR - Failed to import: /home/navneetsajwan/airflow/dags/sql_to_csv.py
Traceback (most recent call last):
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/navneetsajwan/airflow/dags/sql_to_csv.py", line 9, in <module>
    from  mysql_to_csv import tap_mysql_target_csv,today_dir,move_files,detect_schemas,state_file
ModuleNotFoundError: No module named 'mysql_to_csv'
[2021-05-08 01:34:04,867] {scheduler_job.py:641} WARNING - No viable dags retrieved from /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:34:04,976] {scheduler_job.py:190} INFO - Processing /home/navneetsajwan/airflow/dags/sql_to_csv.py took 0.220 seconds
[2021-05-08 01:34:37,959] {scheduler_job.py:182} INFO - Started process (PID=468355) to work on /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:34:37,960] {scheduler_job.py:629} INFO - Processing file /home/navneetsajwan/airflow/dags/sql_to_csv.py for tasks to queue
[2021-05-08 01:34:37,961] {logging_mixin.py:104} INFO - [2021-05-08 01:34:37,961] {dagbag.py:451} INFO - Filling up the DagBag from /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:34:37,988] {logging_mixin.py:104} INFO - [2021-05-08 01:34:37,987] {dagbag.py:308} ERROR - Failed to import: /home/navneetsajwan/airflow/dags/sql_to_csv.py
Traceback (most recent call last):
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/navneetsajwan/airflow/dags/sql_to_csv.py", line 9, in <module>
    from  mysql_to_csv import tap_mysql_target_csv,today_dir,move_files,detect_schemas,state_file
ModuleNotFoundError: No module named 'mysql_to_csv'
[2021-05-08 01:34:37,989] {scheduler_job.py:641} WARNING - No viable dags retrieved from /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:34:38,111] {scheduler_job.py:190} INFO - Processing /home/navneetsajwan/airflow/dags/sql_to_csv.py took 0.157 seconds
[2021-05-08 01:35:15,784] {scheduler_job.py:182} INFO - Started process (PID=469250) to work on /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:35:15,794] {scheduler_job.py:629} INFO - Processing file /home/navneetsajwan/airflow/dags/sql_to_csv.py for tasks to queue
[2021-05-08 01:35:15,795] {logging_mixin.py:104} INFO - [2021-05-08 01:35:15,795] {dagbag.py:451} INFO - Filling up the DagBag from /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:35:15,809] {logging_mixin.py:104} INFO - [2021-05-08 01:35:15,808] {dagbag.py:308} ERROR - Failed to import: /home/navneetsajwan/airflow/dags/sql_to_csv.py
Traceback (most recent call last):
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/navneetsajwan/airflow/dags/sql_to_csv.py", line 9, in <module>
    from  mysql_to_csv import tap_mysql_target_csv,today_dir,move_files,detect_schemas,state_file
ModuleNotFoundError: No module named 'mysql_to_csv'
[2021-05-08 01:35:15,812] {scheduler_job.py:641} WARNING - No viable dags retrieved from /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:35:15,950] {scheduler_job.py:190} INFO - Processing /home/navneetsajwan/airflow/dags/sql_to_csv.py took 0.172 seconds
[2021-05-08 01:35:50,563] {scheduler_job.py:182} INFO - Started process (PID=469761) to work on /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:35:50,565] {scheduler_job.py:629} INFO - Processing file /home/navneetsajwan/airflow/dags/sql_to_csv.py for tasks to queue
[2021-05-08 01:35:50,565] {logging_mixin.py:104} INFO - [2021-05-08 01:35:50,565] {dagbag.py:451} INFO - Filling up the DagBag from /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:35:50,574] {logging_mixin.py:104} INFO - [2021-05-08 01:35:50,573] {dagbag.py:308} ERROR - Failed to import: /home/navneetsajwan/airflow/dags/sql_to_csv.py
Traceback (most recent call last):
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/navneetsajwan/airflow/dags/sql_to_csv.py", line 9, in <module>
    from  mysql_to_csv import tap_mysql_target_csv,today_dir,move_files,detect_schemas,state_file
ModuleNotFoundError: No module named 'mysql_to_csv'
[2021-05-08 01:35:50,575] {scheduler_job.py:641} WARNING - No viable dags retrieved from /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:35:50,671] {scheduler_job.py:190} INFO - Processing /home/navneetsajwan/airflow/dags/sql_to_csv.py took 0.111 seconds
[2021-05-08 01:36:26,250] {scheduler_job.py:182} INFO - Started process (PID=470280) to work on /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:36:26,275] {scheduler_job.py:629} INFO - Processing file /home/navneetsajwan/airflow/dags/sql_to_csv.py for tasks to queue
[2021-05-08 01:36:26,277] {logging_mixin.py:104} INFO - [2021-05-08 01:36:26,277] {dagbag.py:451} INFO - Filling up the DagBag from /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:36:26,291] {logging_mixin.py:104} INFO - [2021-05-08 01:36:26,290] {dagbag.py:308} ERROR - Failed to import: /home/navneetsajwan/airflow/dags/sql_to_csv.py
Traceback (most recent call last):
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/navneetsajwan/airflow/dags/sql_to_csv.py", line 9, in <module>
    from  mysql_to_csv import tap_mysql_target_csv,today_dir,move_files,detect_schemas,state_file
ModuleNotFoundError: No module named 'mysql_to_csv'
[2021-05-08 01:36:26,292] {scheduler_job.py:641} WARNING - No viable dags retrieved from /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:36:26,406] {scheduler_job.py:190} INFO - Processing /home/navneetsajwan/airflow/dags/sql_to_csv.py took 0.176 seconds
[2021-05-08 01:37:09,624] {scheduler_job.py:182} INFO - Started process (PID=471206) to work on /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:37:09,626] {scheduler_job.py:629} INFO - Processing file /home/navneetsajwan/airflow/dags/sql_to_csv.py for tasks to queue
[2021-05-08 01:37:09,628] {logging_mixin.py:104} INFO - [2021-05-08 01:37:09,628] {dagbag.py:451} INFO - Filling up the DagBag from /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:37:09,641] {logging_mixin.py:104} INFO - [2021-05-08 01:37:09,640] {dagbag.py:308} ERROR - Failed to import: /home/navneetsajwan/airflow/dags/sql_to_csv.py
Traceback (most recent call last):
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/navneetsajwan/airflow/dags/sql_to_csv.py", line 9, in <module>
    from  mysql_to_csv import tap_mysql_target_csv,today_dir,move_files,detect_schemas,state_file
ModuleNotFoundError: No module named 'mysql_to_csv'
[2021-05-08 01:37:09,642] {scheduler_job.py:641} WARNING - No viable dags retrieved from /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:37:09,752] {scheduler_job.py:190} INFO - Processing /home/navneetsajwan/airflow/dags/sql_to_csv.py took 0.137 seconds
[2021-05-08 01:37:44,007] {scheduler_job.py:182} INFO - Started process (PID=471707) to work on /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:37:44,011] {scheduler_job.py:629} INFO - Processing file /home/navneetsajwan/airflow/dags/sql_to_csv.py for tasks to queue
[2021-05-08 01:37:44,012] {logging_mixin.py:104} INFO - [2021-05-08 01:37:44,012] {dagbag.py:451} INFO - Filling up the DagBag from /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:37:44,046] {logging_mixin.py:104} INFO - [2021-05-08 01:37:44,045] {dagbag.py:308} ERROR - Failed to import: /home/navneetsajwan/airflow/dags/sql_to_csv.py
Traceback (most recent call last):
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/navneetsajwan/airflow/dags/sql_to_csv.py", line 9, in <module>
    from  mysql_to_csv import tap_mysql_target_csv,today_dir,move_files,detect_schemas,state_file
ModuleNotFoundError: No module named 'mysql_to_csv'
[2021-05-08 01:37:44,047] {scheduler_job.py:641} WARNING - No viable dags retrieved from /home/navneetsajwan/airflow/dags/sql_to_csv.py
[2021-05-08 01:37:44,154] {scheduler_job.py:190} INFO - Processing /home/navneetsajwan/airflow/dags/sql_to_csv.py took 0.159 seconds
