[2021-05-09 18:01:26,151] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: dag_4.python_push_into_target 2021-05-08T05:57:36.499933+00:00 [queued]>
[2021-05-09 18:01:26,181] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: dag_4.python_push_into_target 2021-05-08T05:57:36.499933+00:00 [queued]>
[2021-05-09 18:01:26,181] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-09 18:01:26,181] {taskinstance.py:1069} INFO - Starting attempt 1 of 3
[2021-05-09 18:01:26,181] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-09 18:01:26,355] {taskinstance.py:1089} INFO - Executing <Task(PythonOperator): python_push_into_target> on 2021-05-08T05:57:36.499933+00:00
[2021-05-09 18:01:26,359] {standard_task_runner.py:52} INFO - Started process 6549 to run task
[2021-05-09 18:01:26,364] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dag_4', 'python_push_into_target', '2021-05-08T05:57:36.499933+00:00', '--job-id', '128', '--pool', 'default_pool', '--raw', '--subdir', '/home/navneetsajwan/airflow/dags/dag__4.py', '--cfg-path', '/tmp/tmpxo9ucolf', '--error-file', '/tmp/tmpvi1d7xhd']
[2021-05-09 18:01:26,365] {standard_task_runner.py:77} INFO - Job 128: Subtask python_push_into_target
[2021-05-09 18:01:26,472] {logging_mixin.py:104} INFO - Running <TaskInstance: dag_4.python_push_into_target 2021-05-08T05:57:36.499933+00:00 [running]> on host navneetsajwan-Lenovo-G50-80
[2021-05-09 18:01:26,579] {taskinstance.py:1281} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=navneet@metaorigins.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dag_4
AIRFLOW_CTX_TASK_ID=python_push_into_target
AIRFLOW_CTX_EXECUTION_DATE=2021-05-08T05:57:36.499933+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-05-08T05:57:36.499933+00:00
[2021-05-09 18:01:27,403] {logging_mixin.py:104} INFO - push_test
[2021-05-09 18:01:27,403] {python.py:118} INFO - Done. Returned value was: None
[2021-05-09 18:01:27,408] {taskinstance.py:1185} INFO - Marking task as SUCCESS. dag_id=dag_4, task_id=python_push_into_target, execution_date=20210508T055736, start_date=20210509T123126, end_date=20210509T123127
[2021-05-09 18:01:27,563] {taskinstance.py:1246} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-05-09 18:01:27,578] {local_task_job.py:146} INFO - Task exited with return code 0
