[2021-05-09 18:00:20,915] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: dag_4.move_files 2021-05-08T05:44:22.392437+00:00 [queued]>
[2021-05-09 18:00:20,943] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: dag_4.move_files 2021-05-08T05:44:22.392437+00:00 [queued]>
[2021-05-09 18:00:20,943] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-09 18:00:20,943] {taskinstance.py:1069} INFO - Starting attempt 1 of 3
[2021-05-09 18:00:20,943] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-09 18:00:21,093] {taskinstance.py:1089} INFO - Executing <Task(PythonOperator): move_files> on 2021-05-08T05:44:22.392437+00:00
[2021-05-09 18:00:21,097] {standard_task_runner.py:52} INFO - Started process 6084 to run task
[2021-05-09 18:00:21,105] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dag_4', 'move_files', '2021-05-08T05:44:22.392437+00:00', '--job-id', '114', '--pool', 'default_pool', '--raw', '--subdir', '/home/navneetsajwan/airflow/dags/dag__4.py', '--cfg-path', '/tmp/tmpslg_wgll', '--error-file', '/tmp/tmp_3b36c8n']
[2021-05-09 18:00:21,108] {standard_task_runner.py:77} INFO - Job 114: Subtask move_files
[2021-05-09 18:00:21,246] {logging_mixin.py:104} INFO - Running <TaskInstance: dag_4.move_files 2021-05-08T05:44:22.392437+00:00 [running]> on host navneetsajwan-Lenovo-G50-80
[2021-05-09 18:00:21,354] {taskinstance.py:1281} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=navneet@metaorigins.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dag_4
AIRFLOW_CTX_TASK_ID=move_files
AIRFLOW_CTX_EXECUTION_DATE=2021-05-08T05:44:22.392437+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-05-08T05:44:22.392437+00:00
[2021-05-09 18:00:21,355] {python.py:118} INFO - Done. Returned value was: None
[2021-05-09 18:00:21,362] {taskinstance.py:1185} INFO - Marking task as SUCCESS. dag_id=dag_4, task_id=move_files, execution_date=20210508T054422, start_date=20210509T123020, end_date=20210509T123021
[2021-05-09 18:00:21,691] {taskinstance.py:1246} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-05-09 18:00:21,722] {local_task_job.py:146} INFO - Task exited with return code 0
